version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=8000

  queue:
    build: .
    command: 'python consumer.py'
    depends_on:
      - db
  db:
    image: mysql:8.0  
    container_name: mysql-db-2
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306" 

volumes:
  dbdata:  
