version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:5000'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  
  queue:
    build: .
    # dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  db:
    image: mysql:8.3.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    
